# Generated by Django 5.1.5 on 2025-01-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
