# Generated by Django 5.1.5 on 2025-01-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0002_rename_category_categories_alter_categories_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
