# Generated by Django 5.1.5 on 2025-01-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0005_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
